/*
 * Copyright (c) Parade Technologies, Ltd. 2023.
 */

#include "pip2_cmd_id.h"

char* PIP2_CMD_NAMES[] = {
		[PIP2_CMD_ID_PING]           = "PING",
		[PIP2_CMD_ID_STATUS]         = "STATUS",
		[PIP2_CMD_ID_CTRL]           = "CTRL",
		[PIP2_CMD_ID_CONFIG]         = "CONFIG",
		"Reserved (0x04)",
		[PIP2_CMD_ID_CLEAR]          = "CLEAR",
		[PIP2_CMD_ID_RESET]          = "RESET",
		[PIP2_CMD_ID_VERSION]        = "VERSION",
		"Reserved (0x08)",
		"Reserved (0x09)",
		"Reserved (0x0A)",
		"Reserved (0x0B)",
		"Reserved (0x0C)",
		"Reserved (0x0D)",
		"Reserved (0x0E)",
		"Reserved (0x0F)",
		[PIP2_CMD_ID_FILE_OPEN]      = "FILE_OPEN",
		[PIP2_CMD_ID_FILE_CLOSE]     = "FILE_CLOSE",
		[PIP2_CMD_ID_FILE_READ]      = "FILE_READ",
		[PIP2_CMD_ID_FILE_WRITE]     = "FILE_WRITE",
		[PIP2_CMD_ID_FILE_IOCTL]     = "FILE_IOCTL",
		[PIP2_CMD_ID_FLASH_INFO]     = "FLASH_INFO",
		[PIP2_CMD_ID_EXECUTE]        = "EXECUTE",
		[PIP2_CMD_ID_GET_LAST_ERRNO] = "GET_LAST_ERRNO",
		[PIP2_CMD_ID_EXIT_HOST_MODE] = "EXIT_HOST_MODE",
		[PIP2_CMD_ID_READ_GPIO]      = "READ_GPIO",
		"Reserved (0x1A)",
		"Reserved (0x1B)",
		"Reserved (0x1C)",
		"Reserved (0x1D)",
		"Reserved (0x1E)",
		"Reserved (0x1F)",
		"Reserved (0x20)",
		[PIP2_CMD_ID_EXECUTE_SCAN]   = "EXECUTE_SCAN",
		"Reserved (0x22)",
		"Reserved (0x23)",
		"Reserved (0x24)",
		"Reserved (0x25)",
		"Reserved (0x26)",
		"Reserved (0x27)",
		"Reserved (0x28)",
		"Reserved (0x29)",
		"Reserved (0x2A)",
		"Reserved (0x2B)",
		"Reserved (0x2C)",
		"Reserved (0x2D)",
		"Reserved (0x2E)",
		"Reserved (0x2F)",
		"Reserved (0x30)",
		"Reserved (0x31)",
		"Reserved (0x32)",
		"Reserved (0x33)",
		"Reserved (0x34)",
		"Reserved (0x35)",
		"Reserved (0x36)",
		"Reserved (0x37)",
		"Reserved (0x38)",
		"Reserved (0x39)",
		"Reserved (0x3A)",
		"Reserved (0x3B)",
		"Reserved (0x3C)",
		"Reserved (0x3D)",
		"Reserved (0x3E)",
		"Reserved (0x3F)",
		[PIP2_CMD_ID_SET_PARAMETER]  = "SET_PARAMETER",
		[PIP2_CMD_ID_GET_PARAMETER]  = "GET_PARAMETER",
		[PIP2_CMD_ID_SET_DDI_REG]    = "SET_DDI_REG",
		[PIP2_CMD_ID_GET_DDI_REG]    = "GET_DDI_REG",
		"Reserved (0x44)",
		"Reserved (0x45)",
		"Reserved (0x46)",
		"Reserved (0x47)",
		"Reserved (0x48)",
		"Reserved (0x49)",
		"Reserved (0x4A)",
		"Reserved (0x4B)",
		"Reserved (0x4C)",
		"Reserved (0x4D)",
		"Reserved (0x4E)",
		"Reserved (0x4F)",
		"Reserved (0x50)",
		"Reserved (0x51)",
		"Reserved (0x52)",
		"Reserved (0x53)",
		"Reserved (0x54)",
		"Reserved (0x55)",
		"Reserved (0x56)",
		"Reserved (0x57)",
		"Reserved (0x58)",
		"Reserved (0x59)",
		"Reserved (0x5A)",
		"Reserved (0x5B)",
		"Reserved (0x5C)",
		"Reserved (0x5D)",
		"Reserved (0x5E)",
		"Reserved (0x5F)",
		"Reserved (0x60)",
		"Reserved (0x61)",
		"Reserved (0x62)",
		"Reserved (0x63)",
		"Reserved (0x64)",
		"Reserved (0x65)",
		"Reserved (0x66)",
		"Reserved (0x67)",
		"Reserved (0x68)",
		"Reserved (0x69)",
		"Reserved (0x6A)",
		"Reserved (0x6B)",
		"Reserved (0x6C)",
		"Reserved (0x6D)",
		"Reserved (0x6E)",
		"Reserved (0x6F)",
		[PIP2_CMD_ID_NET_TRANS]      = "NET_TRANS",
		"Reserved (0x71)",
		"Reserved (0x72)",
		"Reserved (0x73)",
		"Reserved (0x74)",
		"Reserved (0x75)",
		"Reserved (0x76)",
		"Reserved (0x77)",
		"Reserved (0x78)",
		"Reserved (0x79)",
		"Reserved (0x7A)",
		"Reserved (0x7B)",
		"Reserved (0x7C)",
		"Reserved (0x7D)",
		"Reserved (0x7E)",
		[PIP2_CMD_ID_EXTEND]         = "EXTEND"
};
