/*
 * Copyright (c) Parade Technologies, Ltd. 2023.
 */

#ifndef PTLIB_PIP_PIP2_STATUS_CODE_H_
#define PTLIB_PIP_PIP2_STATUS_CODE_H_

typedef enum {
	PIP2_STATUS_CODE_SUCCESS                 = 0x00,
	PIP2_STATUS_CODE_BUSY                    = 0x01,
	PIP2_STATUS_CODE_INIT_FAILURE            = 0x02,
	PIP2_STATUS_CODE_FILE_ALREADY_OPEN       = 0x03,
	PIP2_STATUS_CODE_FILE_NOT_OPEN           = 0x04,
	PIP2_STATUS_CODE_IO_FAILURE              = 0x05,
	PIP2_STATUS_CODE_UNKNOWN_IOCTL           = 0x06,
	PIP2_STATUS_CODE_BAD_ADDRESS             = 0x07,
	PIP2_STATUS_CODE_BAD_FILE_NAME           = 0x08,
	PIP2_STATUS_CODE_EOF                     = 0x09,
	PIP2_STATUS_CODE_TOO_MANY_FILES          = 0x0A,
	PIP2_STATUS_CODE_TIMEOUT                 = 0x0B,
	PIP2_STATUS_CODE_ABORTED                 = 0x0C,
	PIP2_STATUS_CODE_BAD_CRC                 = 0x0D,
	PIP2_STATUS_CODE_UNKNOWN_RECORD_TYPE     = 0x0E,
	PIP2_STATUS_CODE_BAD_FRAME               = 0x0F,
	PIP2_STATUS_CODE_NO_PERMISSION           = 0x10,
	PIP2_STATUS_CODE_UNKNOWN_CMD             = 0x11,
	PIP2_STATUS_CODE_INVALID_PARAMS          = 0x12,
	PIP2_STATUS_CODE_IO_ALREADY_ACTIVE       = 0x13,
	PIP2_STATUS_CODE_IO_ABORTED_FOR_SHUTDOWN = 0x14,
	PIP2_STATUS_CODE_INVALID_IMAGE           = 0x15,
	PIP2_STATUS_CODE_UNKNOWN_REGISTER        = 0x16,
	PIP2_STATUS_CODE_BAD_LENGTH              = 0x17,
	PIP2_STATUS_CODE_TRIM_FAILURE            = 0x18,

	NUM_OF_PIP2_STATUS_CODES = 25
} PIP2_Status_Code;

extern char* PIP2_STATUS_CODE_LABELS[NUM_OF_PIP2_STATUS_CODES];

#endif 
