/*
 * Copyright (c) Parade Technologies, Ltd. 2023.
 */

#include "pip3_cmd_id.h"

char* PIP3_CMD_NAMES[] = {
		[PIP3_CMD_ID_PING]                      = "PING",
		[PIP3_CMD_ID_STATUS]                    = "STATUS",
		[PIP3_CMD_ID_CTRL]                      = "CTRL",
		[PIP3_CMD_ID_CONFIG]                    = "CONFIG",
		[PIP3_CMD_ID_SWITCH_IMAGE]              = "SWITCH_IMAGE",
		[PIP3_CMD_ID_SWITCH_ACTIVE_PROCESSOR]   = "SWITCH_ACTIVE_PROCESSOR",
		[PIP3_CMD_ID_RESET]                     = "RESET",
		[PIP3_CMD_ID_VERSION]                   = "VERSION",
		"Reserved (0x08)",
		"Reserved (0x09)",
		"Reserved (0x0A)",
		"Reserved (0x0B)",
		"Reserved (0x0C)",
		"Reserved (0x0D)",
		"Reserved (0x0E)",
		"Reserved (0x0F)",
		[PIP3_CMD_ID_FILE_OPEN]                 = "FILE_OPEN",
		[PIP3_CMD_ID_FILE_CLOSE]                = "FILE_CLOSE",
		[PIP3_CMD_ID_FILE_READ]                 = "FILE_READ",
		[PIP3_CMD_ID_FILE_WRITE]                = "FILE_WRITE",
		[PIP3_CMD_ID_FILE_IOCTL]                = "FILE_IOCTL",
		[PIP3_CMD_ID_FLASH_INFO]                = "FLASH_INFO",
		[PIP3_CMD_ID_EXECUTE]                   = "EXECUTE",
		[PIP3_CMD_ID_GET_LAST_ERRNO]            = "GET_LAST_ERRNO",
		[PIP3_CMD_ID_EXIT_HOST_MODE]            = "EXIT_HOST_MODE",
		[PIP3_CMD_ID_READ_GPIO]                 = "READ_GPIO",
		"Reserved (0x1A)",
		"Reserved (0x1B)",
		"Reserved (0x1C)",
		"Reserved (0x1D)",
		"Reserved (0x1E)",
		"Reserved (0x1F)",
		[PIP3_CMD_ID_VERIFY_DATA_BLOCK_CRC]     = "VERIFY_DATA_BLOCK_CRC",
		[PIP3_CMD_ID_GET_DATA_ROW_SIZE]         = "GET_DATA_ROW_SIZE",
		[PIP3_CMD_ID_READ_DATA_BLOCK]           = "READ_DATA_BLOCK",
		[PIP3_CMD_ID_WRITE_DATA_BLOCK]          = "WRITE_DATA_BLOCK",
		[PIP3_CMD_ID_GET_DATA_STRUCTURE]        = "GET_DATA_STRUCTURE",
		[PIP3_CMD_ID_LOAD_SELF_TEST_PARAM]      = "LOAD_SELF_TEST_PARAM",
		[PIP3_CMD_ID_RUN_SELF_TEST]             = "RUN_SELF_TEST",
		[PIP3_CMD_ID_GET_SELF_TEST_RESULTS]     = "GET_SELF_TEST_RESULTS",
		"Reserved (0x28)",
		[PIP3_CMD_ID_INITIALIZE_BASELINE]       = "INITIALIZE_BASELINE",
		[PIP3_CMD_ID_EXECUTE_SCAN]              = "EXECUTE_SCAN",
		[PIP3_CMD_ID_RETRIEVE_PANEL_SCAN]       = "RETRIEVE_PANEL_SCAN",
		[PIP3_CMD_ID_START_SENSOR_DATA_MODE]    = "START_SENSOR_DATA_MODE",
		[PIP3_CMD_ID_STOP_ASYNC_DEBUG_DATA]     = "STOP_ASYNC_DEBUG_DATA",
		[PIP3_CMD_ID_START_TRACKING_HEATMAP]    = "START_TRACKING_HEATMAP",
		"Reserved (0x2F)",
		[PIP3_CMD_ID_CALIBRATE]                 = "CALIBRATE",
		[PIP3_CMD_ID_START_BOOTLOADER]          = "START_BOOTLOADER",
		[PIP3_CMD_ID_GET_SYSINFO]               = "GET_SYSINFO",
		[PIP3_CMD_ID_SUSPEND_SCAN]              = "SUSPEND_SCAN",
		[PIP3_CMD_ID_RESUME_SCAN]               = "RESUME_SCAN",
		[PIP3_CMD_ID_GET_PARAM]                 = "GET_PARAM",
		[PIP3_CMD_ID_SET_PARAM]                 = "SET_PARAM",
		[PIP3_CMD_ID_GET_NOISE_METRICS]         = "GET_NOISE_METRICS",
		"Reserved (0x38)",
		[PIP3_CMD_ID_ENTER_EASYWAKE_STATE]      = "ENTER_EASYWAKE_STATE",
		[PIP3_CMD_ID_SET_DBG_PARAMETER]         = "SET_DBG_PARAMETER",
		[PIP3_CMD_ID_GET_DBG_PARAMETER]         = "GET_DBG_PARAMETER",
		[PIP3_CMD_ID_SET_DDI_REG]               = "SET_DDI_REG",
		[PIP3_CMD_ID_GET_DDI_REG]               = "GET_DDI_REG",
		[PIP3_CMD_ID_REALTIME_SIGNAL_DATA_MODE] = "REALTIME_SIGNAL_DATA_MODE"
};
